[package]
name = "rx_core_subject_replay"
description = "replat_subject for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
dev = [
    "rx_core/dev",
    "rx_core_traits/dev",
    "rx_core_subject/dev",
    "rx_core_testing/dev",
]
example = [
    "dev",
    "rx_core/example",
    "rx_core_traits/example",
    "rx_core_subject/example",
    "rx_core_testing/example",
]

[dependencies]
ringbuffer = { workspace = true }
rx_core_subject = { workspace = true }
rx_core_traits = { workspace = true }
rx_core_macro_subject_derive = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
