[package]
name = "rx_core_observer_fn"
description = "fn observer for rx_core, it calls a closure"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["dev"]
dev = ["rx_core/dev", "rx_core_traits/dev", "rx_core_testing/dev"]
example = [
    "dev",
    "rx_core/example",
    "rx_core_traits/example",
    "rx_core_testing/example",
]


[dependencies]
rx_core_traits = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
