[package]
name = "rx_core_operator_identity"
description = "identity operator for rx_core; a no-op operator mainly used to define input types for composite operators"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
debug = ["rx_core_testing/debug", "rx_core_common/debug"]

[dependencies]
rx_core_common = { workspace = true }
rx_core_macro_operator_derive = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
derive-where = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
