[package]
name = "rx_core_operator_identity"
description = "identity operator for rx_core; a no-op operator mainly used to define input types for composite operators"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "reactivex",
    "rx_core",
    "rx_core_operator",
    "rx_bevy",
    "rx_bevy_operator",
]

[lints]
workspace = true

[features]
default = []

[dependencies]
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
rx_core_macro_operator_derive = { version = "0.1.0", path = "../rx_core_macro_operator_derive" }
rx_core_macro_subscriber_derive = { version = "0.1.0", path = "../rx_core_macro_subscriber_derive" }
derive-where = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { version = "0.1.0", path = "../rx_core_testing" }
