# https://rust-lang.github.io/mdBook/format/configuration/general.html

[book]
title = "rx_bevy"
authors = ["AlexAegis"]
description = "Usage and development documentation of rx_bevy."
src = "docs"

[build]
build-dir = "target/book"
create-missing = true

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["docs/assets/mermaid.min.js", "docs/mermaid-init.js"]
git-repository-url = "https://github.com/AlexAegis/rx_bevy"
