[package]
name = "rx_core_subscriber_rc"
description = "Non bevy compatible, reference implementation of a reference counted subscriber"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = []
dev = ["rx_bevy/dev", "rx_core_traits/dev", "rx_core_testing/dev"]
example = [
    "dev",
    "rx_bevy/example",
    "rx_core_traits/example",
    "rx_core_testing/example",
]

[dependencies]
rx_core_traits = { workspace = true }
short_type_name = { workspace = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_core_testing = { workspace = true }
rx_core_observable_iterator = { workspace = true }
