[package]
name = "rx_core_subscriber_rc"
description = "A reference counted subscriber for rx_core that unsubscribes its destination only when all of its clones are unsubscribed."
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
debug = [
    "rx_core_observable_iterator/debug",
    "rx_core_testing/debug",
    "rx_core_traits/debug",
]

[dependencies]
rx_core_traits = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
disqualified = { workspace = true }
derive-where = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
rx_core_observable_iterator = { workspace = true }
