[package]
name = "rx_core_operator_switch_all"
description = "switch_all operator for rx_core"
version = "0.1.2"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "rx_core", "rx_core_operator", "rx_bevy", "rx_bevy_operator"]

[lints]
workspace = true

[features]
default = []
pipe = ["rx_core_common/pipe"]
compose = ["dep:rx_core_operator_composite"]

[dependencies]
rx_core_common = { workspace = true }
rx_core_macro_operator_derive = { workspace = true }
rx_core_operator_composite = { workspace = true, optional = true }
rx_core_subscriber_higher_order_switch = { workspace = true }
rx_core_subscriber_higher_order_all = { workspace = true }
derive-where = { workspace = true }
