[package]
name = "rx_core_operator_switch_all"
description = "switch_all operator for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
debug = [
    "rx_core_observable_pipe?/debug",
    "rx_core_operator_composite?/debug",
    "rx_core_subscriber_switch/debug",
    "rx_core_testing/debug",
    "rx_core_traits/debug",
]
pipe = ["dep:rx_core_observable_pipe"]
compose = ["dep:rx_core_operator_composite"]
operator_fn = []

[dependencies]
rx_core_traits = { workspace = true }
rx_core_macro_operator_derive = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
rx_core_observable_pipe = { workspace = true, optional = true }
rx_core_operator_composite = { workspace = true, optional = true }
rx_core_subscriber_switch = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
