[package]
name = "rx_core_subscription_inert"
description = "rx_core inert subscription that can can safely be dropped even with a drop-unsafe context as it starts closed"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "reactivex", "rx_core"]

[lints]
workspace = true

[features]
default = []

[dependencies]
rx_core_common = { workspace = true }
rx_core_macro_subscription_derive = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
