[package]
name = "rx_core_subscription_inert"
description = "rx_core inert subscription that can can safely be dropped even with a drop-unsafe context as it starts closed"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["dev", "debug"]
dev = ["rx_core/dev", "rx_core_traits/dev", "rx_core_testing/dev"]
debug = ["rx_core_traits/debug"]
example = [
    "debug",
    "dev",
    "rx_core/example",
    "rx_core_traits/example",
    "rx_core_testing/example",
]
# TODO: Add a proper debug logger macro
trace = ["dep:short_type_name", "rx_core/trace"]

[dependencies]
rx_core_traits = { workspace = true }
short_type_name = { workspace = true, optional = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
