[package]
name = "rx_core_observable_concat"
description = "concat observable for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
debug = [
    "rx_core_subscriber_higher_order_all/debug",
    "rx_core_subscriber_higher_order_concurrent/debug",
    "rx_core_testing/debug",
    "rx_core_traits/debug",
]
observable_fn = []

default = []
[dependencies]
rx_core_traits = { workspace = true }
rx_core_macro_observable_derive = { workspace = true }
rx_core_subscriber_higher_order_all = { workspace = true }
rx_core_subscriber_higher_order_concurrent = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
