[package]
name = "rx_core_subject_provenance"
description = "provenance_subject for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "rx_core", "rx_core_subject", "rx_bevy", "rx_bevy_subject"]

[lints]
workspace = true

[features]
default = []

[dependencies]
rx_core_subject_behavior = { version = "0.1.0", path = "../rx_core_subject_behavior" }
rx_core_subject_publish = { version = "0.1.0", path = "../rx_core_subject_publish" }
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
rx_core_macro_subject_derive = { version = "0.1.0", path = "../rx_core_macro_subject_derive" }
rx_core_operator_map = { version = "0.1.0", path = "../rx_core_operator_map" }
rx_core_operator_filter = { version = "0.1.0", path = "../rx_core_operator_filter" }
