[package]
name = "rx_bevy_ref_observable_merge"
description = "merge observable for rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["dev"]
dev = [
    "rx_bevy/dev",
    "rx_bevy_common_bounds/dev",
    "rx_bevy_core/dev",
    "rx_bevy_operator_map_into/dev",
    "rx_bevy_ref_subscriber_rc/dev",
    "rx_bevy_testing/dev",
]
example = [
    "dev",
    "rx_bevy/example",
    "rx_bevy_core/example",
    "rx_bevy_operator_map_into/example",
    "rx_bevy_ref_subscriber_rc/example",
    "rx_bevy_testing/example",
]
tick = [
    "rx_bevy/tick",
    "rx_bevy_core/tick",
    "rx_bevy_operator_map_into/tick",
    "rx_bevy_ref_subscriber_rc/tick",
    "rx_bevy_testing/tick",
]

[dependencies]
rx_bevy_core = { workspace = true }
rx_bevy_operator_map_into = { workspace = true }
rx_bevy_ref_subscriber_rc = { workspace = true }
rx_bevy_common_bounds = { workspace = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_bevy_testing = { workspace = true }
