[package]
name = "rx_core_scheduler_ticking"
description = "rx_core mock scheduler for tests and examples"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "rx_core",
    "rx_core_scheduler",
    "rx_bevy",
    "rx_bevy_scheduler",
]

[lints]
workspace = true

[features]
default = []

[dependencies]
derive-where = { workspace = true }
rx_core_macro_executor_derive = { version = "0.1.0", path = "../rx_core_macro_executor_derive" }
rx_core_macro_scheduler_derive = { version = "0.1.0", path = "../rx_core_macro_scheduler_derive" }
rx_core_macro_work_derive = { version = "0.1.0", path = "../rx_core_macro_work_derive" }
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
indexmap = { workspace = true }
