[package]
name = "rx_bevy_operator_take"
description = "take operator for rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["compose", "pipe"]
dev = []
example = ["dev"]
compose = ["dep:rx_bevy_operator_composite"]
pipe = ["dep:rx_bevy_pipe"]
tick = ["rx_bevy_observable/tick"]
reflect = [
    "dep:bevy_reflect",
    "rx_bevy_observable/reflect",
    "rx_bevy_pipe?/reflect",
    "rx_bevy_operator_composite?/reflect",
    "rx_bevy_common_bounds/reflect",
]

[dependencies]
rx_bevy_observable = { workspace = true }
rx_bevy_pipe = { workspace = true, optional = true }
rx_bevy_operator_composite = { workspace = true, optional = true }
rx_bevy_common_bounds = { workspace = true }
bevy_reflect = { workspace = true, optional = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_bevy_testing = { workspace = true }
