[package]
name = "rx_core_operator_composite"
description = "composite operator for rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["pipe"]
dev = [
    "rx_bevy/dev",
    "rx_core_traits/dev",
    "rx_core_observable_pipe?/dev",
    "rx_core_testing/dev",
    "short_type_name/dev",
]
example = [
    "dev",
    "rx_bevy/example",
    "rx_core_traits/example",
    "rx_core_observable_pipe?/example",
    "rx_core_testing/example",
]
pipe = ["dep:rx_core_observable_pipe", "rx_bevy/pipe"]
bevy = ["rx_bevy/bevy", "rx_core_traits/bevy", "rx_core_testing/bevy"]
reflect = ["dep:bevy_reflect", "rx_bevy/reflect", "rx_core_traits/reflect"]

[dependencies]
rx_core_traits = { workspace = true }
rx_core_observable_pipe = { workspace = true, optional = true }
bevy_reflect = { workspace = true, optional = true }
short_type_name = { workspace = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_core_testing = { workspace = true }
