[package]
name = "rx_bevy_operator_filter_map"
description = "filter_map operator for rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["compose", "pipe"]
dev = [
    "rx_bevy/dev",
    "rx_bevy_common_bounds/dev",
    "rx_bevy_core/dev",
    "rx_bevy_operator_composite/dev",
    "rx_bevy_operator_lift_option/dev",
    "rx_bevy_operator_map/dev",
    "rx_bevy_ref_pipe?/dev",
    "rx_bevy_testing/dev",
]
example = [
    "dev",
    "rx_bevy/example",
    "rx_bevy_core/example",
    "rx_bevy_operator_composite/example",
    "rx_bevy_operator_lift_option/example",
    "rx_bevy_operator_map/example",
    "rx_bevy_ref_pipe?/example",
    "rx_bevy_testing/example",
]
compose = [
    "rx_bevy/compose",
    "rx_bevy_operator_lift_option/compose",
    "rx_bevy_operator_map/compose",
]
pipe = [
    "dep:rx_bevy_ref_pipe",
    "rx_bevy/pipe",
    "rx_bevy_operator_composite/pipe",
    "rx_bevy_operator_lift_option/pipe",
    "rx_bevy_operator_map/pipe",
]
bevy = [
    "tick",
    "rx_bevy/bevy",
    "rx_bevy_testing/bevy",
    "rx_bevy_core/bevy",
    "rx_bevy_ref_pipe?/bevy",
    "rx_bevy_operator_composite/bevy",
    "rx_bevy_operator_map/bevy",
    "rx_bevy_operator_lift_option/bevy",
]
tick = [
    "rx_bevy/tick",
    "rx_bevy_testing/tick",
    "rx_bevy_core/tick",
    "rx_bevy_ref_pipe?/tick",
    "rx_bevy_operator_composite/tick",
    "rx_bevy_operator_map/tick",
    "rx_bevy_operator_lift_option/tick",
]
reflect = [
    "dep:bevy_reflect",
    "rx_bevy/reflect",
    "rx_bevy_common_bounds/reflect",
    "rx_bevy_core/reflect",
    "rx_bevy_operator_composite/reflect",
    "rx_bevy_operator_lift_option/reflect",
    "rx_bevy_operator_map/reflect",
    "rx_bevy_ref_pipe?/reflect",
    "rx_bevy_testing/reflect",
]


[dependencies]
rx_bevy_core = { workspace = true }
rx_bevy_operator_composite = { workspace = true }
rx_bevy_operator_map = { workspace = true }
rx_bevy_operator_lift_option = { workspace = true }
rx_bevy_ref_pipe = { workspace = true, optional = true }
rx_bevy_common_bounds = { workspace = true }
bevy_reflect = { workspace = true, optional = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_bevy_testing = { workspace = true }
