[package]
name = "rx_core_observable_iterator"
description = "iterator observable for rx_core"
version = "0.1.1"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "rx_core",
    "rx_core_observable",
    "rx_bevy",
    "rx_bevy_observable",
]

[lints]
workspace = true

[features]
default = []

[dependencies]
rx_core_subscription_inert = { workspace = true }
rx_core_common = { workspace = true }
rx_core_macro_observable_derive = { workspace = true }
