[package]
name = "rx_bevy_subscription_drop"
description = "rx_bevy contextless subscription that can unsubscribe on drop"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["dev", "debug"]
dev = ["rx_bevy/dev", "rx_bevy_core/dev", "rx_bevy_testing/dev"]
debug = ["rx_bevy_core/debug"]
example = [
    "debug",
    "dev",
    "rx_bevy/example",
    "rx_bevy_core/example",
    "rx_bevy_testing/example",
]

[dependencies]
rx_bevy_core = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_bevy_testing = { workspace = true }
