[package]
name = "rx_core_operator_retry"
description = "retry operator for rx_core"
version = "0.1.2"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "rx_core", "rx_core_operator", "rx_bevy", "rx_bevy_operator"]

[lints]
workspace = true

[features]
default = []
pipe = ["rx_core_common/pipe"]

[dependencies]
rx_core_common = { workspace = true }
rx_core_macro_operator_derive = { workspace = true }
rx_core_macro_observable_derive = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
rx_core_observable_connectable = { workspace = true }
derive-where = { workspace = true }
