[package]
name = "rx_bevy_testing"
description = "tools for testing rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = []
dev = ["rx_bevy/dev", "rx_bevy_core/dev"]
example = ["bevy", "dev", "rx_bevy/example", "rx_bevy_core/example"]
bevy = ["rx_bevy/bevy", "rx_bevy_core/bevy"]

[dependencies]
rx_bevy_core = { workspace = true }
short_type_name = { workspace = true }

[dev-dependencies]
rx_bevy = { workspace = true }
