[package]
name = "rx_bevy_plugin"
description = "rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["dev", "reflect", "debug"]
dev = ["bevy/dynamic_linking", "inspector"]
debug = ["bevy/track_location", "rx_bevy_common_bounds/debug"]
serialize = ["rx_bevy_common_bounds/serialize"]
example = [
    "dev",
    "debug",
    "reflect",
    "inspector",
    "bevy/bevy_scene",
    "bevy/bevy_core_pipeline",
    "bevy/bevy_pbr",
    "bevy/bevy_asset",
    "bevy/bevy_render",
    "bevy/bevy_gltf",
    "bevy/bevy_winit",
    "bevy/bevy_picking",
    "bevy/x11",
    "bevy/tonemapping_luts",
]
inspector = [
    "reflect",
    "dep:bevy-inspector-egui",
    "dep:bevy_egui",
    "bevy-inspector-egui/bevy_render",
]
reflect = [
    "dep:bevy_reflect",
    "rx_bevy_common_bounds/reflect",
    "rx_bevy_operator_composite/reflect",
    "rx_bevy_observable/reflect",
]

[dependencies]
bevy_kit_erased_component_registry = { workspace = true }
# rx_bevy dependencies
rx_bevy_observable = { workspace = true, features = ["bevy"] }
rx_bevy_operator_composite = { workspace = true, features = ["tick"] }
rx_bevy_common_bounds = { workspace = true }
# bevy dependencies
bevy_app = { workspace = true }
bevy_derive = { workspace = true }
bevy_ecs = { workspace = true }
bevy_log = { workspace = true }
bevy_reflect = { workspace = true, optional = true }
bevy_time = { workspace = true }
bevy_platform = { workspace = true }
bevy_ptr = { workspace = true }
# third party bevy dependencies
bevy-inspector-egui = { workspace = true, optional = true, features = [] }
bevy_egui = { workspace = true, optional = true }
# misc
derive-where = { workspace = true }
smallvec = { workspace = true }
short_type_name = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }
rx_bevy = { workspace = true, features = ["bevy", "reflect", "tick"] }
rx_bevy_testing = { workspace = true, features = ["tick"] }
examples_common = { workspace = true }
