[package]
name = "rx_core_observable_connectable"
description = "connectable observable for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["dev"]
dev = [
    "rx_core/dev",
    "rx_core_observable_deferred/dev",
    "rx_core_testing/dev",
    "rx_core_traits/dev",
]
example = [
    "dev",
    "rx_core/example",
    "rx_core_observable_deferred/example",
    "rx_core_testing/example",
    "rx_core_traits/example",
]

[dependencies]
rx_core_traits = { workspace = true }
rx_core_macro_observable_derive = { workspace = true }
rx_core_observable_deferred = { workspace = true }
disqualified = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
