[package]
name = "rx_core_operator_enumerate"
description = "enumerate operator for rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["compose", "pipe"]
dev = [
    "rx_bevy/dev",
    "rx_core_traits/dev",
    "rx_core_operator_composite?/dev",
    "rx_core_observable_pipe?/dev",
    "rx_core_testing/dev",
]
example = [
    "dev",
    "rx_bevy/example",
    "rx_core_traits/example",
    "rx_core_operator_composite?/example",
    "rx_core_observable_pipe?/example",
    "rx_core_testing/example",
]
# It's not likely that a simple counter can ever overflow a usize, but if you
# fear that, enable this feature and it will saturate the counter instead of overflowing
saturating_add = []
compose = ["dep:rx_core_operator_composite", "rx_bevy/compose"]
pipe = [
    "dep:rx_core_observable_pipe",
    "rx_bevy/pipe",
    "rx_core_operator_composite?/pipe",
]
bevy = [
    "rx_bevy/bevy",
    "rx_core_traits/bevy",
    "rx_core_operator_composite?/bevy",
    "rx_core_testing/bevy",
]
reflect = [
    "dep:bevy_reflect",
    "rx_bevy/reflect",
    "rx_core_traits/reflect",
    "rx_core_operator_composite?/reflect",
]

[dependencies]
rx_core_traits = { workspace = true }
rx_core_observable_pipe = { workspace = true, optional = true }
rx_core_operator_composite = { workspace = true, optional = true }
bevy_reflect = { workspace = true, optional = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_core_testing = { workspace = true }
