[env]
CARGO_MANIFEST_DIR = "."
RUST_LOG = "debug,wgpu=warn,wgpu_hal=error,naga=warn,bevy_render=warn,bevy_app=warn,winit=warn,bevy_winit=warn,bevy_input=warn,gilrs=warn,gilrs_core=warn,bevy_kit_ik=debug"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
