[package]
name = "rx_core_operator_share"
description = "share operator for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "reactivex",
    "rx_core",
    "rx_core_operator",
    "rx_bevy",
    "rx_bevy_operator",
]

[lints]
workspace = true

[features]
default = []
pipe = ["rx_core_common/pipe"]

[dependencies]
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
rx_core_macro_operator_derive = { version = "0.1.0", path = "../rx_core_macro_operator_derive" }
rx_core_macro_observable_derive = { version = "0.1.0", path = "../rx_core_macro_observable_derive" }
rx_core_observable_connectable = { version = "0.1.0", path = "../rx_core_observable_connectable" }
derive-where = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { version = "0.1.0", path = "../rx_core_testing" }
