[package]
name = "rx_core_observable_zip"
description = "zip observable for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["dev"]
dev = [
    "rx_core/dev",
    "rx_core_traits/dev",
    "rx_core_emission_variants/dev",
    "rx_core_subscriber_rc/dev",
    "rx_core_testing/dev",
]
example = [
    "dev",
    "rx_core/example",
    "rx_core_traits/example",
    "rx_core_emission_variants/example",
    "rx_core_subscriber_rc/example",
    "rx_core_testing/example",
]
observable_fn = []

[dependencies]
rx_core_traits = { workspace = true }
rx_core_macro_observable_derive = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
rx_core_emission_variants = { workspace = true }
rx_core_subscriber_rc = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
