[package]
name = "rx_bevy_operator_filter"
description = "filter operator for rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["compose", "pipe"]
dev = [
    "rx_bevy/dev",
    "rx_bevy_core/dev",
    "rx_bevy_operator_composite?/dev",
    "rx_bevy_ref_pipe?/dev",
    "rx_bevy_testing/dev",
]
example = [
    "dev",
    "rx_bevy/example",
    "rx_bevy_core/example",
    "rx_bevy_operator_composite?/example",
    "rx_bevy_ref_pipe?/example",
    "rx_bevy_testing/example",
]
compose = ["dep:rx_bevy_operator_composite", "rx_bevy/compose"]
pipe = [
    "dep:rx_bevy_ref_pipe",
    "rx_bevy/pipe",
    "rx_bevy_operator_composite?/pipe",
]
bevy = [
    "rx_bevy/bevy",
    "rx_bevy_core/bevy",
    "rx_bevy_operator_composite?/bevy",
    "rx_bevy_testing/bevy",
]
reflect = [
    "dep:bevy_reflect",
    "rx_bevy/reflect",
    "rx_bevy_core/reflect",
    "rx_bevy_operator_composite?/reflect",
]


[dependencies]
rx_bevy_core = { workspace = true }
rx_bevy_ref_pipe = { workspace = true, optional = true }
rx_bevy_operator_composite = { workspace = true, optional = true }
bevy_reflect = { workspace = true, optional = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_bevy_testing = { workspace = true }
