[package]
name = "rx_core_subscriber_higher_order_switch"
description = "switch subscriber for rx_core. Upon receiving an observable, subscribes to it immediately, unsubscribing the previous one."
version = "0.2.1"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "rx_core"]

[lints]
workspace = true

[features]
default = []

[dependencies]
rx_core_macro_subscriber_derive = { workspace = true }
rx_core_common = { workspace = true }
rx_core_subscriber_higher_order = { workspace = true }
