[package]
name = "rx_bevy_ref_subscriber_switch"
description = "Non bevy compatible, reference implementation of a switch subscriber"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = []
dev = [
    "rx_bevy/dev",
    "rx_bevy_core/dev",
    "rx_bevy_subscriber_detached/dev",
    "rx_bevy_ref_subscriber_shared/dev",
    "rx_bevy_testing/dev",
]
example = [
    "dev",
    "rx_bevy/example",
    "rx_bevy_core/example",
    "rx_bevy_subscriber_detached/example",
    "rx_bevy_ref_subscriber_shared/example",
    "rx_bevy_testing/example",
]

[dependencies]
rx_bevy_core = { workspace = true }
rx_bevy_subscriber_detached = { workspace = true }
rx_bevy_ref_subscriber_shared = { workspace = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_bevy_testing = { workspace = true }
