[profile.default]
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
test-threads = 4

[test-groups]
bevy = { max-threads = 2 }

[[profile.ci.overrides]]
filter = 'package(/^rx_bevy(_.*)?$/)'
test-group = 'bevy'
