[package]
name = "rx_core_observable_merge"
description = "merge observable for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
debug = [
    "rx_core_operator_map_into/debug",
    "rx_core_subscriber_rc/debug",
    "rx_core_testing/debug",
    "rx_core_traits/debug",
]
observable_fn = []

[dependencies]
rx_core_operator_map_into = { workspace = true }
rx_core_subscriber_rc = { workspace = true }
rx_core_traits = { workspace = true }
rx_core_macro_observable_derive = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
