[package]
name = "rx_core_observable_merge"
description = "merge observable for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "rx_core",
    "rx_core_observable",
    "rx_bevy",
    "rx_bevy_observable",
]

[lints]
workspace = true

[features]
default = []
observable_fn = []

[dependencies]
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
rx_core_macro_observable_derive = { version = "0.1.0", path = "../rx_core_macro_observable_derive" }
rx_core_subscriber_higher_order_all = { version = "0.1.0", path = "../rx_core_subscriber_higher_order_all" }
rx_core_subscriber_higher_order_concurrent = { version = "0.1.0", path = "../rx_core_subscriber_higher_order_concurrent" }
