[package]
name = "rx_core_common"
version = "0.1.0"
description = "rx_core's core traits and implementations"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "reactivex", "rx_core"]

[lints]
workspace = true

[features]
default = []
pipe = []

[dependencies]
bitflags = { workspace = true }
derive-where = { workspace = true }
disqualified = { workspace = true }
rx_core_macro_observable_derive = { version = "0.1.0", path = "../rx_core_macro_observable_derive" }
rx_core_macro_observer_derive = { version = "0.1.0", path = "../rx_core_macro_observer_derive" }
rx_core_macro_operator_derive = { version = "0.1.0", path = "../rx_core_macro_operator_derive" }
rx_core_macro_subscriber_derive = { version = "0.1.0", path = "../rx_core_macro_subscriber_derive" }
rx_core_macro_subscription_derive = { version = "0.1.0", path = "../rx_core_macro_subscription_derive" }
thiserror = { workspace = true }
variadics_please = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rx_core_macro_observer_derive"] # Used in a doctest
