[package]
name = "rx_core_emission_variants"
description = "Emission variants for rx_core used for observable combinators"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = ["dev"]
dev = ["rx_core/dev", "rx_core_testing/dev", "rx_core_traits/dev"]
example = [
    "dev",
    "rx_core/example",
    "rx_core_testing/example",
    "rx_core_traits/example",
]

[dependencies]
derive-where = { workspace = true }
rx_core_traits = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
