[package]
name = "rx_core_operator_skip"
description = "skip operator for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "reactivex",
    "rx_core",
    "rx_core_operator",
    "rx_bevy",
    "rx_bevy_operator",
]

[lints]
workspace = true

[features]
default = []
compose = ["dep:rx_core_operator_composite"]
pipe = ["rx_core_common/pipe"]

[dependencies]
rx_core_common = { workspace = true }
rx_core_macro_operator_derive = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
rx_core_operator_composite = { workspace = true, optional = true }
derive-where = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
