[package]
name = "rx_core_operator_tap_next"
description = "tap next operator for rx_core, for the simple use cases where you don't want to define an entire observable to peek into one."
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
debug = [
    "dep:disqualified",
    "rx_core_observable_pipe?/debug",
    "rx_core_operator_composite?/debug",
    "rx_core_testing/debug",
    "rx_core_traits/debug",
]
pipe = ["dep:rx_core_observable_pipe"]
compose = ["dep:rx_core_operator_composite"]
operator_fn = []

[dependencies]
rx_core_traits = { workspace = true }
rx_core_observable_pipe = { workspace = true, optional = true }
rx_core_operator_composite = { workspace = true, optional = true }
rx_core_macro_operator_derive = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
disqualified = { workspace = true, optional = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
