[package]
name = "rx_core_operator_tap_next"
description = "tap next operator for rx_core, for the simple use cases where you don't want to define an entire observable to peek into one."
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["pipe", "compose"]
dev = [
    "rx_core/dev",
    "rx_core_traits/dev",
    "rx_core_operator_composite/dev",
    "rx_core_observable_pipe/dev",
    "rx_core_testing/dev",
]
example = [
    "dev",
    "rx_core/example",
    "rx_core_traits/example",
    "rx_core_operator_composite?/example",
    "rx_core_observable_pipe?/example",
    "rx_core_testing/example",
]
pipe = [
    "dep:rx_core_observable_pipe",
    "rx_core/pipe",
    "rx_core_operator_composite?/pipe",
]
compose = ["dep:rx_core_operator_composite", "rx_core/compose"]
trace = ["dep:disqualified", "rx_core/trace"]

[dependencies]
rx_core_traits = { workspace = true }
rx_core_observable_pipe = { workspace = true, optional = true }
rx_core_operator_composite = { workspace = true, optional = true }
disqualified = { workspace = true, optional = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
