[package]
name = "rx_core_operator_tap_next"
description = "tap next operator for rx_core, for the simple use cases where you don't want to define an entire observable to peek into one."
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "rx_core", "rx_core_operator", "rx_bevy", "rx_bevy_operator"]

[lints]
workspace = true

[features]
default = []
pipe = ["rx_core_common/pipe"]
compose = ["dep:rx_core_operator_composite"]

[dependencies]
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
rx_core_operator_composite = { version = "0.1.0", path = "../rx_core_operator_composite", optional = true }
rx_core_macro_operator_derive = { version = "0.1.0", path = "../rx_core_macro_operator_derive" }
rx_core_macro_subscriber_derive = { version = "0.1.0", path = "../rx_core_macro_subscriber_derive" }
derive-where = { workspace = true }
