[package]
name = "rx_core"
version = "0.1.0"
description = "Runtime Agnostic Reactive Extensions"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "reactivex", "rx_core", "rx_bevy"]

[lints]
workspace = true

[features]
default = [
    "all_observables",
    "all_observers",
    "all_operators",
    "all_schedulers",
    "all_subjects",
    "compose",
    "observable_fn",
    "pipe",
]
# Observables
all_observables = [
    "observable_closed",
    "observable_combine_changes",
    "observable_combine_latest",
    "observable_concat",
    "observable_connectable",
    "observable_create",
    "observable_deferred",
    "observable_empty",
    "observable_interval",
    "observable_iterator",
    "observable_iterator_on_tick",
    "observable_join",
    "observable_just",
    "observable_merge",
    "observable_never",
    "observable_throw",
    "observable_timer",
    "observable_zip",
]
observable_closed = ["dep:rx_core_observable_closed"]
observable_combine_changes = ["dep:rx_core_observable_combine_changes"]
observable_combine_latest = ["dep:rx_core_observable_combine_latest"]
observable_concat = ["dep:rx_core_observable_concat"]
observable_connectable = ["dep:rx_core_observable_connectable"]
observable_create = ["dep:rx_core_observable_create"]
observable_deferred = ["dep:rx_core_observable_deferred"]
observable_empty = ["dep:rx_core_observable_empty"]
observable_interval = ["dep:rx_core_observable_interval"]
observable_iterator = ["dep:rx_core_observable_iterator"]
observable_iterator_on_tick = ["dep:rx_core_observable_iterator_on_tick"]
observable_join = ["dep:rx_core_observable_join"]
observable_just = ["dep:rx_core_observable_just"]
observable_merge = ["dep:rx_core_observable_merge"]
observable_never = ["dep:rx_core_observable_never"]
observable_throw = ["dep:rx_core_observable_throw"]
observable_timer = ["dep:rx_core_observable_timer"]
observable_zip = ["dep:rx_core_observable_zip"]
# Observable Creation Functions
observable_fn = [
    "rx_core_observable_closed?/observable_fn",
    "rx_core_observable_combine_changes?/observable_fn",
    "rx_core_observable_combine_latest?/observable_fn",
    "rx_core_observable_concat?/observable_fn",
    "rx_core_observable_create?/observable_fn",
    "rx_core_observable_deferred?/observable_fn",
    "rx_core_observable_empty?/observable_fn",
    "rx_core_observable_interval?/observable_fn",
    "rx_core_observable_join?/observable_fn",
    "rx_core_observable_just?/observable_fn",
    "rx_core_observable_merge?/observable_fn",
    "rx_core_observable_never?/observable_fn",
    "rx_core_observable_throw?/observable_fn",
    "rx_core_observable_timer?/observable_fn",
    "rx_core_observable_zip?/observable_fn",
]
# Observers
all_observers = ["observer_noop", "observer_print", "observer_fn"]
observer_fn = ["dep:rx_core_observer_fn"]
observer_noop = ["dep:rx_core_observer_noop"]
observer_print = ["dep:rx_core_observer_print"]
# Operators
all_operators = [
    "operator_adsr",
    "operator_buffer_count",
    "operator_catch",
    "operator_composite",
    "operator_concat_all",
    "operator_concat_map",
    "operator_delay",
    "operator_dematerialize",
    "operator_end_with",
    "operator_enumerate",
    "operator_error_boundary",
    "operator_exhaust_all",
    "operator_exhaust_map",
    "operator_fallback_when_silent",
    "operator_filter",
    "operator_filter_map",
    "operator_finalize",
    "operator_find",
    "operator_find_index",
    "operator_first",
    "operator_identity",
    "operator_into_result",
    "operator_is_empty",
    "operator_lift_option",
    "operator_lift_result",
    "operator_map",
    "operator_map_error",
    "operator_map_into",
    "operator_map_never",
    "operator_materialize",
    "operator_merge_all",
    "operator_merge_map",
    "operator_on_next",
    "operator_on_subscribe",
    "operator_pairwise",
    "operator_reduce",
    "operator_retry",
    "operator_scan",
    "operator_share",
    "operator_skip",
    "operator_start_with",
    "operator_switch_all",
    "operator_switch_map",
    "operator_take",
    "operator_tap",
    "operator_tap_next",
    "operator_with_latest_from",
]
operator_adsr = ["dep:rx_core_operator_adsr"]
operator_buffer_count = ["dep:rx_core_operator_buffer_count"]
operator_catch = ["dep:rx_core_operator_catch"]
operator_composite = ["dep:rx_core_operator_composite"]
operator_concat_all = ["dep:rx_core_operator_concat_all"]
operator_concat_map = ["dep:rx_core_operator_concat_map"]
operator_delay = ["dep:rx_core_operator_delay"]
operator_dematerialize = ["dep:rx_core_operator_dematerialize"]
operator_end_with = ["dep:rx_core_operator_end_with"]
operator_enumerate = ["dep:rx_core_operator_enumerate"]
operator_error_boundary = ["dep:rx_core_operator_error_boundary"]
operator_exhaust_all = ["dep:rx_core_operator_exhaust_all"]
operator_exhaust_map = ["dep:rx_core_operator_exhaust_map"]
operator_fallback_when_silent = ["dep:rx_core_operator_fallback_when_silent"]
operator_filter = ["dep:rx_core_operator_filter"]
operator_filter_map = ["dep:rx_core_operator_filter_map"]
operator_finalize = ["dep:rx_core_operator_finalize"]
operator_find = ["dep:rx_core_operator_find"]
operator_find_index = ["dep:rx_core_operator_find_index"]
operator_first = ["dep:rx_core_operator_first"]
operator_identity = ["dep:rx_core_operator_identity"]
operator_into_result = ["dep:rx_core_operator_into_result"]
operator_is_empty = ["dep:rx_core_operator_is_empty"]
operator_lift_option = ["dep:rx_core_operator_lift_option"]
operator_lift_result = ["dep:rx_core_operator_lift_result"]
operator_map = ["dep:rx_core_operator_map"]
operator_map_error = ["dep:rx_core_operator_map_error"]
operator_map_into = ["dep:rx_core_operator_map_into"]
operator_map_never = ["dep:rx_core_operator_map_never"]
operator_materialize = ["dep:rx_core_operator_materialize"]
operator_merge_all = ["dep:rx_core_operator_merge_all"]
operator_merge_map = ["dep:rx_core_operator_merge_map"]
operator_on_next = ["dep:rx_core_operator_on_next"]
operator_on_subscribe = ["dep:rx_core_operator_on_subscribe"]
operator_pairwise = ["dep:rx_core_operator_pairwise"]
operator_reduce = ["dep:rx_core_operator_reduce"]
operator_retry = ["dep:rx_core_operator_retry"]
operator_scan = ["dep:rx_core_operator_scan"]
operator_share = ["dep:rx_core_operator_share"]
operator_skip = ["dep:rx_core_operator_skip"]
operator_start_with = ["dep:rx_core_operator_start_with"]
operator_switch_all = ["dep:rx_core_operator_switch_all"]
operator_switch_map = ["dep:rx_core_operator_switch_map"]
operator_take = ["dep:rx_core_operator_take"]
operator_tap = ["dep:rx_core_operator_tap"]
operator_tap_next = ["dep:rx_core_operator_tap_next"]
operator_with_latest_from = ["dep:rx_core_operator_with_latest_from"]
pipe = [
    "rx_core_operator_adsr?/pipe",
    "rx_core_operator_buffer_count?/pipe",
    "rx_core_operator_catch?/pipe",
    "rx_core_operator_concat_all?/pipe",
    "rx_core_operator_concat_map?/pipe",
    "rx_core_operator_delay?/pipe",
    "rx_core_operator_dematerialize?/pipe",
    "rx_core_operator_end_with?/pipe",
    "rx_core_operator_enumerate?/pipe",
    "rx_core_operator_error_boundary?/pipe",
    "rx_core_operator_exhaust_all?/pipe",
    "rx_core_operator_exhaust_map?/pipe",
    "rx_core_operator_fallback_when_silent?/pipe",
    "rx_core_operator_filter?/pipe",
    "rx_core_operator_filter_map?/pipe",
    "rx_core_operator_finalize?/pipe",
    "rx_core_operator_find?/pipe",
    "rx_core_operator_find_index?/pipe",
    "rx_core_operator_first?/pipe",
    "rx_core_operator_into_result?/pipe",
    "rx_core_operator_is_empty?/pipe",
    "rx_core_operator_lift_option?/pipe",
    "rx_core_operator_lift_result?/pipe",
    "rx_core_operator_map?/pipe",
    "rx_core_operator_map_error?/pipe",
    "rx_core_operator_map_into?/pipe",
    "rx_core_operator_map_never?/pipe",
    "rx_core_operator_materialize?/pipe",
    "rx_core_operator_merge_all?/pipe",
    "rx_core_operator_merge_map?/pipe",
    "rx_core_operator_on_next?/pipe",
    "rx_core_operator_on_subscribe?/pipe",
    "rx_core_operator_pairwise?/pipe",
    "rx_core_operator_reduce?/pipe",
    "rx_core_operator_retry?/pipe",
    "rx_core_operator_scan?/pipe",
    "rx_core_operator_share?/pipe",
    "rx_core_operator_skip?/pipe",
    "rx_core_operator_start_with?/pipe",
    "rx_core_operator_switch_all?/pipe",
    "rx_core_operator_switch_map?/pipe",
    "rx_core_operator_take?/pipe",
    "rx_core_operator_tap?/pipe",
    "rx_core_operator_tap_next?/pipe",
    "rx_core_operator_with_latest_from?/pipe",
]
compose = [
    "operator_composite",
    "rx_core_operator_adsr?/compose",
    "rx_core_operator_buffer_count?/compose",
    "rx_core_operator_catch?/compose",
    "rx_core_operator_concat_all?/compose",
    "rx_core_operator_concat_map?/compose",
    "rx_core_operator_delay?/compose",
    "rx_core_operator_dematerialize?/compose",
    "rx_core_operator_end_with?/compose",
    "rx_core_operator_enumerate?/compose",
    "rx_core_operator_error_boundary?/compose",
    "rx_core_operator_exhaust_all?/compose",
    "rx_core_operator_exhaust_map?/compose",
    "rx_core_operator_fallback_when_silent?/compose",
    "rx_core_operator_filter?/compose",
    "rx_core_operator_filter_map?/compose",
    "rx_core_operator_finalize?/compose",
    "rx_core_operator_find?/compose",
    "rx_core_operator_find_index?/compose",
    "rx_core_operator_first?/compose",
    "rx_core_operator_into_result?/compose",
    "rx_core_operator_is_empty?/compose",
    "rx_core_operator_lift_option?/compose",
    "rx_core_operator_lift_result?/compose",
    "rx_core_operator_map?/compose",
    "rx_core_operator_map_error?/compose",
    "rx_core_operator_map_into?/compose",
    "rx_core_operator_map_never?/compose",
    "rx_core_operator_materialize?/compose",
    "rx_core_operator_merge_all?/compose",
    "rx_core_operator_merge_map?/compose",
    "rx_core_operator_on_next?/compose",
    "rx_core_operator_on_subscribe?/compose",
    "rx_core_operator_pairwise?/compose",
    "rx_core_operator_reduce?/compose",
    "rx_core_operator_scan?/compose",
    "rx_core_operator_skip?/compose",
    "rx_core_operator_start_with?/compose",
    "rx_core_operator_switch_all?/compose",
    "rx_core_operator_switch_map?/compose",
    "rx_core_operator_take?/compose",
    "rx_core_operator_tap?/compose",
    "rx_core_operator_tap_next?/compose",
    "rx_core_operator_with_latest_from?/compose",
]
# Schedulers
all_schedulers = ["scheduler_ticking"]
scheduler_ticking = ["dep:rx_core_scheduler_ticking"]
# Subjects
all_subjects = [
    "subject_async",
    "subject_behavior",
    "subject_provenance",
    "subject_publish",
    "subject_replay",
]
subject_async = ["dep:rx_core_subject_async"]
subject_behavior = ["dep:rx_core_subject_behavior"]
subject_provenance = ["dep:rx_core_subject_provenance"]
subject_publish = ["dep:rx_core_subject_publish"]
subject_replay = ["dep:rx_core_subject_replay"]

[dependencies]
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
# Observables
rx_core_observable_closed = { version = "0.1.0", path = "../rx_core_observable_closed", optional = true }
rx_core_observable_combine_changes = { version = "0.1.0", path = "../rx_core_observable_combine_changes", optional = true }
rx_core_observable_combine_latest = { version = "0.1.0", path = "../rx_core_observable_combine_latest", optional = true }
rx_core_observable_concat = { version = "0.1.0", path = "../rx_core_observable_concat", optional = true }
rx_core_observable_connectable = { version = "0.1.0", path = "../rx_core_observable_connectable", optional = true }
rx_core_observable_create = { version = "0.1.0", path = "../rx_core_observable_create", optional = true }
rx_core_observable_deferred = { version = "0.1.0", path = "../rx_core_observable_deferred", optional = true }
rx_core_observable_empty = { version = "0.1.0", path = "../rx_core_observable_empty", optional = true }
rx_core_observable_interval = { version = "0.1.0", path = "../rx_core_observable_interval", optional = true }
rx_core_observable_iterator = { version = "0.1.0", path = "../rx_core_observable_iterator", optional = true }
rx_core_observable_iterator_on_tick = { version = "0.1.0", path = "../rx_core_observable_iterator_on_tick", optional = true }
rx_core_observable_join = { version = "0.1.0", path = "../rx_core_observable_join", optional = true }
rx_core_observable_just = { version = "0.1.0", path = "../rx_core_observable_just", optional = true }
rx_core_observable_merge = { version = "0.1.0", path = "../rx_core_observable_merge", optional = true }
rx_core_observable_never = { version = "0.1.0", path = "../rx_core_observable_never", optional = true }
rx_core_observable_throw = { version = "0.1.0", path = "../rx_core_observable_throw", optional = true }
rx_core_observable_timer = { version = "0.1.0", path = "../rx_core_observable_timer", optional = true }
rx_core_observable_zip = { version = "0.1.0", path = "../rx_core_observable_zip", optional = true }
# Observers
rx_core_observer_fn = { version = "0.1.0", path = "../rx_core_observer_fn", optional = true }
rx_core_observer_noop = { version = "0.1.0", path = "../rx_core_observer_noop", optional = true }
rx_core_observer_print = { version = "0.1.0", path = "../rx_core_observer_print", optional = true }
# Operators
rx_core_operator_adsr = { version = "0.1.0", path = "../rx_core_operator_adsr", optional = true }
rx_core_operator_buffer_count = { version = "0.1.0", path = "../rx_core_operator_buffer_count", optional = true }
rx_core_operator_catch = { version = "0.1.0", path = "../rx_core_operator_catch", optional = true }
rx_core_operator_composite = { version = "0.1.0", path = "../rx_core_operator_composite", optional = true }
rx_core_operator_concat_all = { version = "0.1.0", path = "../rx_core_operator_concat_all", optional = true }
rx_core_operator_concat_map = { version = "0.1.0", path = "../rx_core_operator_concat_map", optional = true }
rx_core_operator_delay = { version = "0.1.0", path = "../rx_core_operator_delay", optional = true }
rx_core_operator_dematerialize = { version = "0.1.0", path = "../rx_core_operator_dematerialize", optional = true }
rx_core_operator_end_with = { version = "0.1.0", path = "../rx_core_operator_end_with", optional = true }
rx_core_operator_enumerate = { version = "0.1.0", path = "../rx_core_operator_enumerate", optional = true }
rx_core_operator_error_boundary = { version = "0.1.0", path = "../rx_core_operator_error_boundary", optional = true }
rx_core_operator_exhaust_all = { version = "0.1.0", path = "../rx_core_operator_exhaust_all", optional = true }
rx_core_operator_exhaust_map = { version = "0.1.0", path = "../rx_core_operator_exhaust_map", optional = true }
rx_core_operator_fallback_when_silent = { version = "0.1.0", path = "../rx_core_operator_fallback_when_silent", optional = true }
rx_core_operator_filter = { version = "0.1.0", path = "../rx_core_operator_filter", optional = true }
rx_core_operator_filter_map = { version = "0.1.0", path = "../rx_core_operator_filter_map", optional = true }
rx_core_operator_finalize = { version = "0.1.0", path = "../rx_core_operator_finalize", optional = true }
rx_core_operator_find = { version = "0.1.0", path = "../rx_core_operator_find", optional = true }
rx_core_operator_find_index = { version = "0.1.0", path = "../rx_core_operator_find_index", optional = true }
rx_core_operator_first = { version = "0.1.0", path = "../rx_core_operator_first", optional = true }
rx_core_operator_identity = { version = "0.1.0", path = "../rx_core_operator_identity", optional = true }
rx_core_operator_into_result = { version = "0.1.0", path = "../rx_core_operator_into_result", optional = true }
rx_core_operator_is_empty = { version = "0.1.0", path = "../rx_core_operator_is_empty", optional = true }
rx_core_operator_lift_option = { version = "0.1.0", path = "../rx_core_operator_lift_option", optional = true }
rx_core_operator_lift_result = { version = "0.1.0", path = "../rx_core_operator_lift_result", optional = true }
rx_core_operator_map = { version = "0.1.0", path = "../rx_core_operator_map", optional = true }
rx_core_operator_map_error = { version = "0.1.0", path = "../rx_core_operator_map_error", optional = true }
rx_core_operator_map_into = { version = "0.1.0", path = "../rx_core_operator_map_into", optional = true }
rx_core_operator_map_never = { version = "0.1.0", path = "../rx_core_operator_map_never", optional = true }
rx_core_operator_materialize = { version = "0.1.0", path = "../rx_core_operator_materialize", optional = true }
rx_core_operator_merge_all = { version = "0.1.0", path = "../rx_core_operator_merge_all", optional = true }
rx_core_operator_merge_map = { version = "0.1.0", path = "../rx_core_operator_merge_map", optional = true }
rx_core_operator_on_next = { version = "0.1.0", path = "../rx_core_operator_on_next", optional = true }
rx_core_operator_on_subscribe = { version = "0.1.0", path = "../rx_core_operator_on_subscribe", optional = true }
rx_core_operator_pairwise = { version = "0.1.0", path = "../rx_core_operator_pairwise", optional = true }
rx_core_operator_reduce = { version = "0.1.0", path = "../rx_core_operator_reduce", optional = true }
rx_core_operator_retry = { version = "0.1.0", path = "../rx_core_operator_retry", optional = true }
rx_core_operator_scan = { version = "0.1.0", path = "../rx_core_operator_scan", optional = true }
rx_core_operator_share = { version = "0.1.0", path = "../rx_core_operator_share", optional = true }
rx_core_operator_skip = { version = "0.1.0", path = "../rx_core_operator_skip", optional = true }
rx_core_operator_start_with = { version = "0.1.0", path = "../rx_core_operator_start_with", optional = true }
rx_core_operator_switch_all = { version = "0.1.0", path = "../rx_core_operator_switch_all", optional = true }
rx_core_operator_switch_map = { version = "0.1.0", path = "../rx_core_operator_switch_map", optional = true }
rx_core_operator_take = { version = "0.1.0", path = "../rx_core_operator_take", optional = true }
rx_core_operator_tap = { version = "0.1.0", path = "../rx_core_operator_tap", optional = true }
rx_core_operator_tap_next = { version = "0.1.0", path = "../rx_core_operator_tap_next", optional = true }
rx_core_operator_with_latest_from = { version = "0.1.0", path = "../rx_core_operator_with_latest_from", optional = true }
# Schedulers
rx_core_scheduler_ticking = { version = "0.1.0", path = "../rx_core_scheduler_ticking", optional = true }
# Subjects
rx_core_subject_async = { version = "0.1.0", path = "../rx_core_subject_async", optional = true }
rx_core_subject_behavior = { version = "0.1.0", path = "../rx_core_subject_behavior", optional = true }
rx_core_subject_provenance = { version = "0.1.0", path = "../rx_core_subject_provenance", optional = true }
rx_core_subject_publish = { version = "0.1.0", path = "../rx_core_subject_publish", optional = true }
rx_core_subject_replay = { version = "0.1.0", path = "../rx_core_subject_replay", optional = true }

[dev-dependencies]
rx_core_testing = { version = "0.1.0", path = "../rx_core_testing" }
rx_core_notification_store = { version = "0.1.0", path = "../rx_core_notification_store" }
rx_core_subscriber_higher_order_concurrent = { version = "0.1.0", path = "../rx_core_subscriber_higher_order_concurrent" }
rx_core_subscriber_higher_order_exhaust = { version = "0.1.0", path = "../rx_core_subscriber_higher_order_exhaust" }
rx_core_subscriber_higher_order_switch = { version = "0.1.0", path = "../rx_core_subscriber_higher_order_switch" }
