[package]
name = "rx_core"
version = "0.1.0"
description = "COntextful Reactive Extensions"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = [
    "all_observables",
    "all_observers",
    "all_operators",
    "all_subjects",
    "compose",
    "observable_fn",
    "pipe",
]
debug = [
    "rx_core_observable_combine_latest?/debug",
    "rx_core_observable_connectable?/debug",
    "rx_core_observable_deferred?/debug",
    "rx_core_observable_interval?/debug",
    "rx_core_observable_iterator?/debug",
    "rx_core_observable_iterator_on_tick?/debug",
    "rx_core_observable_merge?/debug",
    "rx_core_observable_of?/debug",
    "rx_core_observable_pipe?/debug",
    "rx_core_observable_throw?/debug",
    "rx_core_observable_zip?/debug",
    "rx_core_observer_fn?/debug",
    "rx_core_observer_noop?/debug",
    "rx_core_observer_print?/debug",
    "rx_core_operator_adsr?/debug",
    "rx_core_operator_composite?/debug",
    "rx_core_operator_enumerate?/debug",
    "rx_core_operator_error_boundary?/debug",
    "rx_core_operator_fallback_when_silent?/debug",
    "rx_core_operator_filter?/debug",
    "rx_core_operator_filter_map?/debug",
    "rx_core_operator_finalize?/debug",
    "rx_core_operator_identity?/debug",
    "rx_core_operator_into_result?/debug",
    "rx_core_operator_lift_option?/debug",
    "rx_core_operator_lift_result?/debug",
    "rx_core_operator_map?/debug",
    "rx_core_operator_map_into?/debug",
    "rx_core_operator_scan?/debug",
    "rx_core_operator_skip?/debug",
    "rx_core_operator_switch_all?/debug",
    "rx_core_operator_switch_map?/debug",
    "rx_core_operator_take?/debug",
    "rx_core_operator_tap_next?/debug",
    "rx_core_subject?/debug",
    "rx_core_subject_behavior?/debug",
    "rx_core_subject_replay?/debug",
    "rx_core_testing/debug",
    "rx_core_traits/debug",
]
# Observables
all_observables = [
    "observable_combine_latest",
    "observable_connectable",
    "observable_deferred",
    "observable_interval",
    "observable_iterator",
    "observable_iterator_on_tick",
    "observable_merge",
    "observable_of",
    "observable_pipe",
    "observable_throw",
    "observable_zip",
]
observable_combine_latest = ["dep:rx_core_observable_combine_latest"]
observable_connectable = ["dep:rx_core_observable_connectable"]
observable_deferred = ["dep:rx_core_observable_deferred"]
observable_interval = ["dep:rx_core_observable_interval"]
observable_iterator = ["dep:rx_core_observable_iterator"]
observable_iterator_on_tick = ["dep:rx_core_observable_iterator_on_tick"]
observable_merge = ["dep:rx_core_observable_merge"]
observable_of = ["dep:rx_core_observable_of"]
observable_pipe = ["dep:rx_core_observable_pipe"]
observable_throw = ["dep:rx_core_observable_throw"]
observable_zip = ["dep:rx_core_observable_zip"]
# Observable Creation Functions
observable_fn = [
    "rx_core_observable_combine_latest?/observable_fn",
    "rx_core_observable_deferred?/observable_fn",
    "rx_core_observable_merge?/observable_fn",
    "rx_core_observable_of?/observable_fn",
    "rx_core_observable_throw?/observable_fn",
    "rx_core_observable_zip?/observable_fn",
]
# Observers
all_observers = ["observer_noop", "observer_print", "observer_fn"]
observer_fn = ["dep:rx_core_observer_fn"]
observer_noop = ["dep:rx_core_observer_noop"]
observer_print = ["dep:rx_core_observer_print"]
# Operators
all_operators = [
    "operator_adsr",
    "operator_composite",
    "operator_enumerate",
    "operator_error_boundary",
    "operator_fallback_when_silent",
    "operator_filter",
    "operator_filter_map",
    "operator_finalize",
    "operator_identity",
    "operator_into_result",
    "operator_lift_option",
    "operator_lift_result",
    "operator_map",
    "operator_map_into",
    "operator_merge_all",
    "operator_merge_map",
    "operator_reduce",
    "operator_scan",
    "operator_skip",
    "operator_switch_all",
    "operator_switch_map",
    "operator_take",
    "operator_tap_next",
]
operator_adsr = ["dep:rx_core_operator_adsr"]
operator_composite = ["dep:rx_core_operator_composite"]
operator_enumerate = ["dep:rx_core_operator_enumerate"]
operator_error_boundary = ["dep:rx_core_operator_error_boundary"]
operator_fallback_when_silent = ["dep:rx_core_operator_fallback_when_silent"]
operator_filter = ["dep:rx_core_operator_filter"]
operator_filter_map = ["dep:rx_core_operator_filter_map"]
operator_finalize = ["dep:rx_core_operator_finalize"]
operator_identity = ["dep:rx_core_operator_identity"]
operator_into_result = ["dep:rx_core_operator_into_result"]
operator_lift_option = ["dep:rx_core_operator_lift_option"]
operator_lift_result = ["dep:rx_core_operator_lift_result"]
operator_map = ["dep:rx_core_operator_map"]
operator_map_into = ["dep:rx_core_operator_map_into"]
operator_merge_all = ["dep:rx_core_operator_merge_all"]
operator_merge_map = ["dep:rx_core_operator_merge_map"]
operator_reduce = ["dep:rx_core_operator_reduce"]
operator_scan = ["dep:rx_core_operator_scan"]
operator_skip = ["dep:rx_core_operator_skip"]
operator_switch_all = ["dep:rx_core_operator_switch_all"]
operator_switch_map = ["dep:rx_core_operator_switch_map"]
operator_take = ["dep:rx_core_operator_take"]
operator_tap_next = ["dep:rx_core_operator_tap_next"]
pipe = [
    "observable_pipe",
    "rx_core_operator_adsr?/pipe",
    "rx_core_operator_enumerate?/pipe",
    "rx_core_operator_error_boundary?/pipe",
    "rx_core_operator_fallback_when_silent?/pipe",
    "rx_core_operator_filter?/pipe",
    "rx_core_operator_filter_map?/pipe",
    "rx_core_operator_finalize?/pipe",
    "rx_core_operator_into_result?/pipe",
    "rx_core_operator_lift_option?/pipe",
    "rx_core_operator_lift_result?/pipe",
    "rx_core_operator_map?/pipe",
    "rx_core_operator_map_into?/pipe",
    "rx_core_operator_merge_all?/pipe",
    "rx_core_operator_merge_map?/pipe",
    "rx_core_operator_reduce?/pipe",
    "rx_core_operator_scan?/pipe",
    "rx_core_operator_skip?/pipe",
    "rx_core_operator_switch_all?/pipe",
    "rx_core_operator_switch_map?/pipe",
    "rx_core_operator_take?/pipe",
    "rx_core_operator_tap_next?/pipe",
]
compose = [
    "operator_composite",
    "rx_core_operator_adsr?/compose",
    "rx_core_operator_enumerate?/compose",
    "rx_core_operator_error_boundary?/compose",
    "rx_core_operator_fallback_when_silent?/compose",
    "rx_core_operator_filter?/compose",
    "rx_core_operator_filter_map?/compose",
    "rx_core_operator_finalize?/compose",
    "rx_core_operator_into_result?/compose",
    "rx_core_operator_lift_option?/compose",
    "rx_core_operator_lift_result?/compose",
    "rx_core_operator_map?/compose",
    "rx_core_operator_map_into?/compose",
    "rx_core_operator_merge_all?/compose",
    "rx_core_operator_merge_map?/compose",
    "rx_core_operator_reduce?/compose",
    "rx_core_operator_scan?/compose",
    "rx_core_operator_skip?/compose",
    "rx_core_operator_switch_all?/compose",
    "rx_core_operator_switch_map?/compose",
    "rx_core_operator_take?/compose",
    "rx_core_operator_tap_next?/compose",
]
# Subjects
all_subjects = ["subject", "subject_behavior", "subject_replay"]
subject = ["dep:rx_core_subject"]
subject_behavior = ["dep:rx_core_subject_behavior"]
subject_replay = ["dep:rx_core_subject_replay"]

[dependencies]
rx_core_traits = { workspace = true }
# Observables
rx_core_observable_combine_latest = { workspace = true, optional = true }
rx_core_observable_connectable = { workspace = true, optional = true }
rx_core_observable_deferred = { workspace = true, optional = true }
rx_core_observable_interval = { workspace = true, optional = true }
rx_core_observable_iterator = { workspace = true, optional = true }
rx_core_observable_iterator_on_tick = { workspace = true, optional = true }
rx_core_observable_merge = { workspace = true, optional = true }
rx_core_observable_of = { workspace = true, optional = true }
rx_core_observable_throw = { workspace = true, optional = true }
rx_core_observable_zip = { workspace = true, optional = true }
# Pipe
rx_core_observable_pipe = { workspace = true, optional = true }
# Observers
rx_core_observer_fn = { workspace = true, optional = true }
rx_core_observer_noop = { workspace = true, optional = true }
rx_core_observer_print = { workspace = true, optional = true }
# Operators
rx_core_operator_adsr = { workspace = true, optional = true }
rx_core_operator_composite = { workspace = true, optional = true }
rx_core_operator_enumerate = { workspace = true, optional = true }
rx_core_operator_error_boundary = { workspace = true, optional = true }
rx_core_operator_fallback_when_silent = { workspace = true, optional = true }
rx_core_operator_filter = { workspace = true, optional = true }
rx_core_operator_filter_map = { workspace = true, optional = true }
rx_core_operator_finalize = { workspace = true, optional = true }
rx_core_operator_identity = { workspace = true, optional = true }
rx_core_operator_lift_option = { workspace = true, optional = true }
rx_core_operator_lift_result = { workspace = true, optional = true }
rx_core_operator_map = { workspace = true, optional = true }
rx_core_operator_map_into = { workspace = true, optional = true }
rx_core_operator_merge_all = { workspace = true, optional = true }
rx_core_operator_merge_map = { workspace = true, optional = true }
rx_core_operator_reduce = { workspace = true, optional = true }
rx_core_operator_scan = { workspace = true, optional = true }
rx_core_operator_skip = { workspace = true, optional = true }
rx_core_operator_switch_all = { workspace = true, optional = true }
rx_core_operator_switch_map = { workspace = true, optional = true }
rx_core_operator_take = { workspace = true, optional = true }
rx_core_operator_tap_next = { workspace = true, optional = true }
rx_core_operator_into_result = { workspace = true, optional = true }
# Subjects
rx_core_subject = { workspace = true, optional = true }
rx_core_subject_behavior = { workspace = true, optional = true }
rx_core_subject_replay = { workspace = true, optional = true }

[dev-dependencies]
rx_core_testing = { workspace = true }
