[package]
name = "rx_core_traits"
version = "0.1.0"
description = "rx_core's core traits and implementations"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
debug = []
pipe = []

[dependencies]
derive-where = { workspace = true }
disqualified = { workspace = true }
rx_core_macro_observable_derive = { workspace = true }
rx_core_macro_operator_derive = { workspace = true }
rx_core_macro_subscriber_derive = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true }
