[package]
name = "rx_core_traits"
version = "0.1.0"
description = "rx_core's core traits and implementations"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["dev_panic_on_dropped_active_subscriptions"]
dev = [
    "dev_panic_on_dropped_active_subscriptions",
    "rx_core/dev",
    "rx_core_testing/dev",
]
example = ["dev", "rx_core/example", "rx_core_testing/example"]
debug = []
# Keep this turned on for development, turn it off for production!
# Depending on the context a subscription needs to perform an unsubscribe,
# not all subscriptions can be automatically unsubscribed when they are dropped
# The subscriptions when dropped, will check if they had been unsubscribed, and
# during development, this should panic so you notice it. For production, you
# can decide if you want to keep your program running or crash for mishandled
# subscriptions.
dev_panic_on_dropped_active_subscriptions = []

[dependencies]
smallvec = { workspace = true }
disqualified = { workspace = true }
derive-where = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
