[package]
# TODO: Rename to rx_core_observable_pipe it's an observable
name = "rx_core_observable_pipe"
description = "pipe operator for rx_bevy"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = []
dev = ["rx_bevy/dev", "rx_core_traits/dev", "rx_core_testing/dev"]
example = [
    "dev",
    "rx_bevy/example",
    "rx_core_traits/example",
    "rx_core_testing/example",
]

[dependencies]
rx_core_traits = { workspace = true }

[dev-dependencies]
rx_bevy = { workspace = true }
rx_core_testing = { workspace = true }
