[package]
name = "rx_core_operator_switch_map"
description = "switch_map operator for rx_core"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license-file.workspace = true

[lints]
workspace = true

[features]
default = ["compose", "pipe"]
dev = [
    "rx_core/dev",
    "rx_core_traits/dev",
    "rx_core_operator_composite?/dev",
    "rx_core_operator_finalize/dev",
    "rx_core_operator_map/dev",
    "rx_core_observable_pipe?/dev",
    "rx_core_subscriber_switch/dev",
    "rx_core_testing/dev",
]
example = [
    "dev",
    "rx_core/example",
    "rx_core_traits/example",
    "rx_core_operator_composite?/example",
    "rx_core_operator_finalize/example",
    "rx_core_operator_map/example",
    "rx_core_observable_pipe?/example",
    "rx_core_subscriber_switch/example",
    "rx_core_testing/example",
]
compose = [
    "dep:rx_core_operator_composite",
    "rx_core/compose",
    "rx_core_operator_finalize/compose",
    "rx_core_operator_map/compose",
]
pipe = [
    "dep:rx_core_observable_pipe",
    "rx_core/pipe",
    "rx_core_operator_composite?/pipe",
    "rx_core_operator_finalize/pipe",
    "rx_core_operator_map/pipe",
]
trace = ["dep:short_type_name", "rx_core/trace"]

[dependencies]
rx_core_traits = { workspace = true }
rx_core_observable_pipe = { workspace = true, optional = true }
rx_core_operator_composite = { workspace = true, optional = true }
rx_core_subscriber_switch = { workspace = true }
short_type_name = { workspace = true, optional = true }

[dev-dependencies]
rx_core = { workspace = true }
rx_core_testing = { workspace = true }
rx_core_operator_finalize = { workspace = true }
rx_core_operator_map = { workspace = true }
