[package]
name = "rx_core_observer_print"
description = "print observer for rx_core, it prints out received values"
version = "0.1.0"
readme = "readme.md"
publish = false

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "reactivex",
    "rx_core",
    "rx_core_observer",
    "rx_bevy",
    "rx_bevy_observer",
]

[lints]
workspace = true

[features]
default = []
debug = ["rx_core_testing/debug", "rx_core_common/debug"]

[dependencies]
rx_core_common = { workspace = true }
rx_core_macro_observer_derive = { workspace = true }

[dev-dependencies]
rx_core = { workspace = true, default-features = true }
rx_core_testing = { workspace = true }
