[package]
name = "rx_core_observer_noop"
description = "noop observer for rx_core, it doesn't do anything"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = [
    "rx",
    "reactivex",
    "rx_core",
    "rx_core_observer",
    "rx_bevy",
    "rx_bevy_observer",
]

[lints]
workspace = true

[features]
default = []

[dependencies]
rx_core_common = { version = "0.1.0", path = "../rx_core_common" }
rx_core_macro_observer_derive = { version = "0.1.0", path = "../rx_core_macro_observer_derive" }
derive-where = { workspace = true }
