[package]
name = "rx_core_macro_executor_derive"
description = "rx_core executor derive, implements associated type only traits"
version = "0.1.0"
readme = "readme.md"
publish = true

edition.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true
keywords = ["rx", "reactivex", "rx_core"]

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
rx_core_macro_common = { workspace = true }

[dev-dependencies]
rx_core_macro_scheduler_derive = { workspace = true }
rx_core_common = { workspace = true }
rx_core_scheduler_ticking = { workspace = true }
